### ISSUE TITLE
Combos only based on first card submitted of dupes

### ISSUE THREAD

**Issue by orogvany** [cartoon-battle/cartoon-battle.github.io#1]
If i have 1* and add a 1**
it shows one combo, but with stats just for the first (lower) combo.
It would be nice if this would show either all combos, or the highest of cards submitted.
Since it recalcuates stats on that first card.

**Comment by mlebkowski** [comment]
Yeah, you’re right, I fixed it now, it will show the one with better stats. Thanks!
