### ISSUE TITLE
Epic double fused background image is wrong

### ISSUE THREAD

**Issue by vogonistic** [cartoon-battle/cartoon-battle.github.io#2]
https://cartoon-battle.narzekasz.pl/deck/frames/epic3notrait2.png should have double fused background. The image seems identical to the single fused background. The images doesn't seemed to be published from this repo so I can't do a PR for it.

Can be tested by adding a epic double fused card to the deck builder.

Awesome job!

**Comment by mlebkowski** [comment]
All the assets are [from the fan kit](http://www.kongregate.com/forums/727066-general/topics/663912-official-game-wiki-and-fan-kit), and the double fused epic frames were missing, so I replaced them with single fused. If you have the skill to fix them somehow, just send me the files and I’ll update them on the CDN

**Comment by vogonistic** [comment]
The backgrounds from here seems correct: https://drive.google.com/open?id=0Bxr_qvfBViHkMXR1MVltQVMxQm8

Maybe they released a newer fan kit or someone else fixed the problem.

**Comment by mlebkowski** [comment]
Yeah, they just updated the frames! It will be up as soon as the cache invalidates, it may be even now.
