### ISSUE TITLE
"Show" and "Trait" icons don't match

### ISSUE THREAD

**Issue by Dansiman** [cartoon-battle/cartoon-battle.github.io#7]
Currently, the cartoon-battle site uses a **yellow 4-point** star icon for skills that only target *shows*, and a **white 4-point** star icon for skills that only target *traits*. The game uses a **yellow 4-point** star icon for skills that only target *traits*, and a **blue 3-point** star icon for skills that only target *shows*.
Please adjust these icons to match how the game displays them. In particular, it's confusing that the original yellow icon represents traits in the game, but shows on the site.
Here are the original Fan Kit images of both icons, in case you need them.
![skill_special](https://user-images.githubusercontent.com/19188912/34745415-14ea2e84-f556-11e7-8851-59a2ef6afc3d.png)
![skill_targetip](https://user-images.githubusercontent.com/19188912/34745417-150267f6-f556-11e7-9690-6657840c7e69.png)

**Comment by Dansiman** [comment]
I created Pull Request #8 with the appropriate code changes to implement this. From looking at [your existing yellow star icon](https://cartoon-battle.narzekasz.pl/deck/skills/skill_special.png), I can see that you will need to make a modification to the blue icon I've provided - I can't do it myself, because I don't have any image editing software other than MS Paint, which won't preserve the transparency - to add additional padding like the yellow one has, and then you'll just need to upload it to your image repository with the name `skill_targetIP.png` and you should be able to just merge that pull request and this will be fixed. 😃

**Comment by mlebkowski** [comment]
thx, fixed in 4117d36
